In [30]:
import  cv2
import numpy as np

#load the picture
img=cv2.imread('A12N13A_0.jpg')
cv2.namedWindow('1',cv2.WINDOW_NORMAL)
cv2.namedWindow('2',cv2.WINDOW_NORMAL)
#rgb2gray
graytemp=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray1 = cv2.GaussianBlur(graytemp,(7,7),1,1)
print(gray1)
cv2.imshow('kk',gray1)
res = cv2.threshold(gray1,130,255,cv2.THRESH_BINARY_INV)
#vtitch = np.vstack((gray1, res[1]))
cv2.imshow('2',res[1])


#霍夫变换圆检测
#1 para：gray image
#2 para: detect method
#3 para: 1(use default value for me)
#4 para: the minist distance between two circles
#5 para: canny() higher threshold,the higher detect the obvious edge
#6 para: the hiher ,detect the more obvious circle
#7 8 para: min R,max R
circles= cv2.HoughCircles(res[1],cv2.HOUGH_GRADIENT,1,200,param1=200,param2=25,minRadius=10,maxRadius=100)

if np.any(circles):
    #根据检测到圆的信息，画出每一个圆
    for circle in circles[0]:
        #圆的基本信息
        x=int(circle[0])
        y=int(circle[1])
        r=int(circle[2])
        print(x,y,r)
        #在原图用指定颜色标记出圆的位置
        img=cv2.circle(img,(x,y),r,(0,0,255),10)
        #cv.rectangle(src,(29,195),(46,206),(0,0,255),1);#画方框
#显示新图像
cv2.imshow('1',img)

#按任意键退出
cv2.waitKey(0)
cv2.destroyAllWindows()

[[84 85 86 ... 56 53 52]
 [84 85 86 ... 55 53 52]
 [84 85 86 ... 52 53 53]
 ...
 [97 96 96 ... 62 60 59]
 [97 96 96 ... 60 58 57]
 [97 96 96 ... 59 57 56]]
571 657 55
560 355 56
